### ISSUE TITLE
black letters instead of white 

### ISSUE THREAD

**Issue by moshpirit** [n0x-styles/wikipedia-dark#1]
[here](https://es.wikipedia.org/wiki/Gradiente#Aproximaci.C3.B3n_lineal_de_una_funci.C3.B3) "donde /formula es el gradiente evaluado en" appears in black instead of grey/white

**Comment by n0x-styles** [comment]
Hello, this has been fixed in commit 0cad097

**Comment by moshpirit** [comment]
Thank you! :)
