### ISSUE TITLE
Style is broken in french

### ISSUE THREAD

**Issue by pdesjardins90** [n0x-styles/wikipedia-dark#34]
The background surrounding the content is all white and the content is squeezed in a narrower middle column

It doesn't seem to affect other non-english languages

**Comment by vfauth** [comment]
Same here

**Comment by n0x-styles** [comment]
It should be solved with the newest commit.

**Comment by pdesjardins90** [comment]
Thanks! You almost fixed it completely, but there's still something wrong with the left menu:

<img width="1327" alt="Capture d’écran, le 2021-03-24 à 11 27 35 a m" src="https://user-images.githubusercontent.com/6752776/112337160-0e6cec80-8c94-11eb-8b3b-bb399f721b91.png">

**Comment by n0x-styles** [comment]
Are you sure you updated the theme? It seems to be fixed on my side. Could
you please give me some details about your browser and configuration?
Thanks a lot for your feedback!

Le mercredi 24 mars 2021, Philippe Desjardins ***@***.***> a
écrit :

**Comment by n0x-styles** [comment]
I found the problem when zooming to a screen smaller than 1080p. It must be
fixed now!

**Comment by pdesjardins90** [comment]
Yay it's totally fixed now, thank you kind sir (or madam)!
