### ISSUE TITLE
Wikipedia changes broke this style

### ISSUE THREAD

**Issue by coman49** [n0x-styles/wikipedia-dark#43]
Wikipedia just made changes to the way it looks - https://wikimediafoundation.org/wikipedia-desktop/

Unfortunately, that broke the area outside the actual text including the contents table.

![Screenshot 2023-01-19 212637](https://user-images.githubusercontent.com/28886182/213604916-baf647d5-47c9-42c5-812f-4212acc3aec1.png)

**Comment by Joecstarr** [comment]
You can switch back to the old style in the user settings. 

![image](https://user-images.githubusercontent.com/52646388/214485252-34d78932-0da6-4523-b740-6faa954775af.png)

**Comment by coman49** [comment]
Sorry but how do you get to those user settings? My settings look like this:

![Screenshot 2023-01-25 005402](https://user-images.githubusercontent.com/28886182/214491246-22f3c264-afaf-42c5-842c-e63712e47be7.png)

**Comment by Joecstarr** [comment]
It's on wikipedia not the style.

**Comment by coman49** [comment]
Got it, thanks. Had to create an account there. This works, but I do like the new wikipedia style better, would be great if this style was updated for it.

**Comment by n0x-styles** [comment]
Most of those problems must be fixed by commit #9163323, update the style in your browser!
