### ISSUE TITLE
h2 background for "Today's Featured List"

### ISSUE THREAD

**Issue by The-Twisted-Samurai** [n0x-styles/wikipedia-dark#7]
I don't understand why or how, but the h2 background for "Today's Featured List" has reverted back to the old Wikipedia colour (Pink-ish). 

Here's the image for the same - [image](https://i.imgur.com/vS1Js9N.png)

**Comment by n0x-styles** [comment]
Hi, this issue has been fixed in commit 48a3fd1

**Comment by The-Twisted-Samurai** [comment]
Oh thanks!
